
services:
  request-service:
    container_name : request-service
    build:
      context: .
      dockerfile: ./request-service/Dockerfile
    ports:
        - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ASIAUDGUOL3KTHSDK4OS
      AWS_SECRET_ACCESS_KEY: /xrurqTIibCTeYZahdJG27CLBMSFErc6XN2Bb5Mp
      AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEFoaCXVzLXdlc3QtMiJIMEYCIQCj99J+s5W98Dukafimh0tXxsi6Gj3BnTDXXJfsdDZA6QIhALDrYn8T/q4OMauMzoIZMa2uj/Ju1n9B7MS/eNK1YTiyKrICCKP//////////wEQABoMMjgxNzY1ODk1ODkzIgxz0po9WFaZyveTZDcqhgKW4/q/sG48tqegCNGQOPQD61JpC5mcEsOsbypXI7Py12BVkZ5JaWYbAx9mQLERIgpiXOe1QZk5gc0HGTOz7GjGlWTbKtdohEgIMEuWPhlneXs4K1hWhDhpsqGRawDlBNLJmlm7g9t0vbZKnakUT0hQxi9EAOKE72XnJ+fG+Q6fOEHv3MQSLa+nQJ1TGDo05CZVc0Ne/01o5ggVPIylQdm2I+RGr40NPK0DYiUe8tWynx6/fRAsTd3f+SGaZLR1P45OFV/CsfKcbnDnlBv06d0TPTgl8LL8vF5UrAkxXHfSDUD+2PjPa7RHDpU0KkQl5Nnn4U8ZVaJA/kuJHuMmfivivKNK9ViFMOyi9LcGOpwB1CBU5owmO7SAv5jkR1dvL7YRRBZ03RW6c/WpEG3pTqR7uDFbE2G++Lo4DSGSB8MTKRWVHP8go2o4rrK0RI0ajQXvUPUkqERsYHu2hPZ1oBntpsNqo+m2OOCa1xuzgEVB3L7BvlphlbY1ez0RBeV82PlQdoKvOhH1ZjOxggn3H75kLoZA8SApDDFnD6PRUXmkDNSAmyafDTwU2b4P
      AWS_REGION: us-east-1

  management-service:
    container_name: management-service
    build:
      context: .
      dockerfile: ./management-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      AWS_ACCESS_KEY_ID: ASIAUDGUOL3KTHSDK4OS
      AWS_SECRET_ACCESS_KEY: /xrurqTIibCTeYZahdJG27CLBMSFErc6XN2Bb5Mp
      AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEFoaCXVzLXdlc3QtMiJIMEYCIQCj99J+s5W98Dukafimh0tXxsi6Gj3BnTDXXJfsdDZA6QIhALDrYn8T/q4OMauMzoIZMa2uj/Ju1n9B7MS/eNK1YTiyKrICCKP//////////wEQABoMMjgxNzY1ODk1ODkzIgxz0po9WFaZyveTZDcqhgKW4/q/sG48tqegCNGQOPQD61JpC5mcEsOsbypXI7Py12BVkZ5JaWYbAx9mQLERIgpiXOe1QZk5gc0HGTOz7GjGlWTbKtdohEgIMEuWPhlneXs4K1hWhDhpsqGRawDlBNLJmlm7g9t0vbZKnakUT0hQxi9EAOKE72XnJ+fG+Q6fOEHv3MQSLa+nQJ1TGDo05CZVc0Ne/01o5ggVPIylQdm2I+RGr40NPK0DYiUe8tWynx6/fRAsTd3f+SGaZLR1P45OFV/CsfKcbnDnlBv06d0TPTgl8LL8vF5UrAkxXHfSDUD+2PjPa7RHDpU0KkQl5Nnn4U8ZVaJA/kuJHuMmfivivKNK9ViFMOyi9LcGOpwB1CBU5owmO7SAv5jkR1dvL7YRRBZ03RW6c/WpEG3pTqR7uDFbE2G++Lo4DSGSB8MTKRWVHP8go2o4rrK0RI0ajQXvUPUkqERsYHu2hPZ1oBntpsNqo+m2OOCa1xuzgEVB3L7BvlphlbY1ez0RBeV82PlQdoKvOhH1ZjOxggn3H75kLoZA8SApDDFnD6PRUXmkDNSAmyafDTwU2b4P
      AWS_REGION: us-east-1
